### ISSUE TITLE
Module listing for `Ash.Api` shows DSL docs for `Ash.Api.Dsl` instead

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#103]
I came across this while trying to find an example for #91 - I found that a bunch of deprecated functions exist in Ash.Api (as seen here https://hexdocs.pm/ash/Ash.Api.html) but those docs aren't visible in AshHQ.

You can search for Ash.Api and see the correct result - 

<img width="1115" alt="Screenshot 2023-02-16 at 2 20 41 pm" src="https://user-images.githubusercontent.com/543859/219284710-04f42d13-0ee9-49f1-ad97-7ecdb50c2cf0.png">

Clicking the search result takes you to https://ash-hq.org/docs/module/ash/latest/ash-api, which looks like the right URL, but it shows the docs for Ash.Api.Dsl instead.

Using the left nav has the same effect - 

* DSLs & Extensions -> Ash.Api -> Ash.Api.Dsl goes to https://ash-hq.org/docs/dsl/ash/latest/api with the DSL content
* Code -> Resources -> Ash.Api goes to https://ash-hq.org/docs/module/ash/latest/ash-api - different URL, but same content.

**Comment by sevenseacat** [comment]
Noticed that the Code links for Ash.Resource and Ash.Registry do the same thing. Possibly duplicated names?

**Comment by zachdaniel** [comment]
Its doing a weird thing where it matches the `target` of an extension and will route to that extension instead. I think this was to solve for cases where the target for a DSL wasn't imported and so that was a dead link even though it was a natural thing to link to. I'll leave it in just in case I think, but if we find a module I'll set `extension: nil` so that you get routed to the module.

**Comment by zachdaniel** [comment]
nvm, if there are dead links to modules we'll just fix the links or fix the modules. I'll just remove the weird `module -> extension` linking.

**Comment by zachdaniel** [comment]
Fixed in 7789755
