### ISSUE TITLE
Broken Website Links

### ISSUE THREAD

**Issue by ck-schmidi** [ash-project/ash_hq#124]
**Brief Description**

I found 8 broken links on the AshHQ Website:

* <https://hexdocs.pm/mix/master/Mix.Tasks.Format.html> (linked from <http://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/getting-started-with-ash-authentication-phoenix>)
* <https://hexdocs.pm/ash_json_api/DSL:-AshJsonApi.Api.html> (linked from <http://ash-hq.org/docs/guides/ash_json_api/latest/dsls/DSL:-AshJsonApi.Api>)
* <https://www.ash-hq.org/documentation/monitoring.md> (linked from <http://ash-hq.org/docs/guides/ash_graphql/latest/tutorials/getting-started-with-graphql>)
* <https://www.ash-hq.org/documentation/topics/open-api.md> (linked from <http://ash-hq.org/docs/guides/ash_json_api/latest/tutorials/getting-started-with-json-api>)
* <https://www.postgresql.org/docs/current/pgtrgm.htmlhere/> (linked from <http://ash-hq.org/docs/guides/ash_postgres/latest/topics/postgres-expressions>)
* <https://hexdocs.pm/ash_json_api/DSL:-AshJsonApi.Resource.html> (linked from http://ash-hq.org/docs/guides/ash_json_api/latest/dsls/DSL:-AshJsonApi.Resource)
* <https://www.ash-hq.org/blog/spark> (linked from <http://ash-hq.org/blog/there-are-macros>)
* <https://ash-hq.org/module/reactor/latest/reactor-builder> (linked from <http://ash-hq.org/docs/guides/reactor/latest/tutorials/getting-started-with-reactor>)

**Steps to reproduce the bug**

Open single links with browser

**Comment by zachdaniel** [comment]
Thank you! This is very helpful. We will be revamping all documentation soon, and this list will be very helpful

**Comment by sevenseacat** [comment]
After the docs restructure, there are now some broken links in the Glossary (on AshHQ only, on hexdocs they're fine?)

https://ash-hq.org/docs/guides/ash/latest/topics/glossary

The find-out-more link in the Domains section and Resources section are fine, but most of the rest are broken, eg. the Actors & Authorization link goes to https://ash-hq.org/documentation/topics/security/actors-and-authorization.md instead of https://ash-hq.org/docs/guides/ash/latest/security/actors-and-authorization .

**Comment by zachdaniel** [comment]
I've addressed all of these links, and the importer issues. These will be fixed as each package is imported due to having a new version published.
