### ISSUE TITLE
Excessive scrollbars

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_hq#2]
On chrome, brave, chromium on linux

![image](https://user-images.githubusercontent.com/637350/180947713-9d2d1863-640b-4926-af14-1b0b9f654796.png)

**Comment by zachdaniel** [comment]
I'm actually not sure how much I can do about this. I increased the space used so it's not all jammed together, and set it to auto instead of scroll so it at least won't show them if they aren't necessary. But AFAIK scrollable divs like that will always show scrollbars on certain OS. I'm not a front end wiz though so open to ideas to improve!

**Comment by totaltrash** [comment]
Yep, looks much better, the extra padding makes heaps of difference

![image](https://user-images.githubusercontent.com/637350/181400120-6a8e94a9-f06d-447a-bf58-f78196a9c2c1.png)
