### ISSUE TITLE
"Selected Packages" list always lists main Ash package even when it is not selected

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#54]
**Brief Description**

Additionally, the pill for Ash doesn't reflect the version that may be selected as an active package.

**Steps to reproduce the bug**

* Visit docs page of ash-hq https://www.ash-hq.org/docs/guides/ash/latest/tutorials/get-started
* Edit "Selected packages" and set Ash to "hidden"
* `ash | 2.4.2` still appears in sidebar as a selected package (even though it is not)
* Edit "Selected packages" and set Ash to a version that isn't latest or 2.4.2
* `ash | 2.4.2` still appears in sidebar as a selected package

**Comment by zachdaniel** [comment]
I think this has to do with the fact that when you visit a link, we always (temporarily) ensure that the library/version combo is shown as a selected version. So the fact that you're looking at a guide as of version 2.4.2 forces that version pill to show that way. From a UI perspective this is clearly weird, but otherwise the sidebar wouldn't show the thing you are looking at. Going to need to think a bit about how to resolve that.

**Comment by sevenseacat** [comment]
Ah right, and it does work like that - if I specifically go look at some docs within AshPhoenix then I can remove/change version of the Ash package.

Possible ways to handle it:
* If I'm looking at docs for a func in ash 2.4 and I change to ash 2.3 (which has the same function) then change to be the 2.3 version of the docs
* If I'm looking at docs for a func in ash 2.4 and I change to ash 2.3 (which does NOT have the same function) then go to the docs homepage
* If I'm looking at docs for a func in ash 2.4 and I hide the ash package then go to the docs homepage
