### ISSUE TITLE
Search is not returning full matches before partial matches

### ISSUE THREAD

**Issue by martinstannard** [ash-project/ash_hq#90]
**Brief Description**

When searching for a `for_create` the results show a lot of hits for `create` before any for `for_create`.

**Steps to reproduce the bug**

Search for `for_create`, observe results

**Context**

![Selection_256](https://user-images.githubusercontent.com/2578/217711104-67b83c9a-85b2-4798-bbec-d3d9426b836c.png)

**Comment by zachdaniel** [comment]
What someone could do to help improve search is the following things:
1. adjust the content weighting to be less swingy. Each searchable entity has a `content_weight` and I think maybe that is overpowering this.
2. adjust searching so that it checks for a name match (probably using trigram). This was done before, but was removed when I optimized search. If you hunt through the repo history you'd probably find it. This may not be necessary if adjusting the weighting solves for this

**Comment by sevenseacat** [comment]
This could also be related to #36
